version: "3.9"

services:
  gallery-client:
    build:
        context: .
        dockerfile: Dockerfile_client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://gallery-server:5001"

  gallery-server:
    build:
        context: .
        dockerfile: Dockerfile_server
    ports:
      - "5001:5001"


  nginx:
    build :
      dockerfile: Dockerfile_nginx
    ports:
      - "5000:5000"
      - "80:80"
    volumes:
      - ./gallery-server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./gallery-server/images/:/usr/share/nginx/html/images
    depends_on:
      - gallery-client
      - gallery-server