FROM python:3.9-alpine

EXPOSE 5000

WORKDIR ./gallery-server/app

RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev

ADD requirements.txt .
RUN python -m pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
