version: "3.9"

services:
  gallery-client:
    build:
        context: .
        dockerfile: /gallery-client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://api:5000"

  gallery-server:
    build:
         context: .
        dockerfile: /gallery-server/Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api